name: dio_refresh_bot
description: Dio interceptor which makes refresh token mechanism simple, flexible and reactive.
version: 2.1.2
homepage: https://github.com/flutterbots/flutterbots

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bot_storage: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.3
  meta: ^1.7.0
  rxdart: ^0.27.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.1.0

