name: bot_storage
description: A useful package provide an interface to handle read, write and delete operations in reactive way
version: 1.1.0
homepage: https://github.com/flutterbots/flutterbots

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  meta: ^1.15.0
  rxdart: ^0.28.0


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

